[package]
org = "chuhaashanan"
name = "sfdc_opportunity_update_to_db"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.22.jar"
